version: "2"
linters:
  default: all
  disable:
    - testpackage
    - gosmopolitan
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/aasanchez/ocpp16messages
    revive:
      rules:
        - name: var-naming
          severity: warning
          disabled: false
          exclude: [""]
          arguments:
            - ["ID"] # AllowList
output:
  formats:
    text:
      path: golangci-lint.txt
      print-linter-name: true
      print-issued-lines: true
      colors: false
