run:
  deadline: 5m
  tests: false
  skip-dirs:
    - vendor/
  go: '1.21'

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - gofmt
    - errcheck
    - gosimple
    - unused
    - misspell

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
  exclude:
    - "should have comment"
    - "always receives"

output:
  format: colored-line-number
