run:
  timeout: 2m

linters:
  enable:
    - govet
    - revive
    - gofmt
    - goimports
    - staticcheck
    - unused
    - gocritic
    - gosimple
    - errcheck
    - structcheck
    - typecheck

issues:
  exclude-use-default: false

output:
  format: colored-line-number
