version: "2"
linters:
  default: all
  disable:
    - testpackage
    - gosmopolitan
  settings:
    varnamelen:
      min-name-length: 1
output:
  formats:
    text:
      path: golangci-lint.txt
      print-linter-name: true
      print-issued-lines: true
      colors: false
    json:
      path: golangci-lint.json
