name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Go 1.23 • Lint • Test • Benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

      - name: Build
        run: go build ./...

      - name: Test with coverage
        run: |
          mkdir -p .testresults
          go test ./... -coverpkg=./core,./authorize -coverprofile=.testresults/coverage.out -v

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: .testresults/coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Enforce coverage threshold
        run: |
          total=$(go tool cover -func=.testresults/coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          threshold=20.0
          echo "Total coverage: $total%"
          awk -v total=$total -v threshold=$threshold 'BEGIN {exit (total+0 < threshold)}'

      - name: Run benchmarks
        run: |
          mkdir -p .benchmark
          go test -bench=. -benchmem ./benchmark > .benchmark/results.txt

      - name: Run CPU & memory profiling
        run: |
          mkdir -p .pprof
          go test -bench=ValidateMessage -cpuprofile=.pprof/cpu.prof ./benchmark
          go test -bench=. -memprofile=.pprof/mem.prof ./benchmark
          go tool pprof -svg .pprof/cpu.prof > .pprof/cpu.svg || true
          go tool pprof -svg .pprof/mem.prof > .pprof/mem.svg || true

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: .benchmark/results.txt

      - name: Upload profiling data
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-profiles
          path: .pprof
